"""Lightweight, versioned contracts shared by Kolmogorov experiment code."""


FORCED_MODE_QUADRATURE_BASIS_VERSION = "forced_mode_quadrature_v1"

LEGACY_SPEED_GRID_OBSERVATION_MODE = "speed_grid"
LEGACY_SPEED_GRID_OBSERVATION_VERSION = "speed_grid_v1"
SIGNED_FORCED_MODE_OBSERVATION_MODE = "signed_forced_mode"
SIGNED_FORCED_MODE_OBSERVATION_VERSION = "signed_forced_mode_v1"

OBSERVATION_CONTRACT_VERSIONS = {
    LEGACY_SPEED_GRID_OBSERVATION_MODE: LEGACY_SPEED_GRID_OBSERVATION_VERSION,
    SIGNED_FORCED_MODE_OBSERVATION_MODE: SIGNED_FORCED_MODE_OBSERVATION_VERSION,
}
